version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: aiforscience-local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx-local.conf:/etc/nginx/nginx.conf
      - ./ssl-local:/etc/nginx/ssl
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - aiforscience-network

  # 本地SSL证书生成服务
  mkcert:
    image: alpine:latest
    container_name: aiforscience-mkcert
    volumes:
      - ./ssl-local:/ssl
    command: >
      sh -c "
        apk add --no-cache mkcert &&
        mkcert -install &&
        mkcert -key-file /ssl/localhost-key.pem -cert-file /ssl/localhost.pem localhost 127.0.0.1 &&
        chmod 644 /ssl/localhost.pem &&
        chmod 600 /ssl/localhost-key.pem &&
        echo 'SSL证书生成完成！'
      "
    networks:
      - aiforscience-network

networks:
  aiforscience-network:
    driver: bridge 